{% set name = "hypothesis-networkx" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/hypothesis_networkx-{{ version }}.tar.gz
  sha256: a8211dec83cbeea6b3fcddd9fc6879d852d15f7a3bc2896045057d0cd67ebfbe

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pbr
    - pip
    - python {{ python_min }}
    - setuptools >=30.3.0
  run:
    - attrs >=19.2.0
    - hypothesis
    - networkx ~=2.0
    - pbr
    - python >={{ python_min }}

test:
  source_files:
    - tests
  imports:
    - hypothesis_networkx
  commands:
    - pip check
    - pytest -vvv --capture=tee-sys tests
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/pckroon/hypothesis-networkx
  summary: A Hypothesis strategy for generating NetworkX graphs
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
